name: metrics
on:
  schedule:
    - cron: '0 8 * * *'   # daily at 08:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # create a fine-grained PAT with public_repo + read:user
          user: KaveeshJeffry
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Colombo
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_habits: yes
          plugin_habits_from: 100
          plugin_habits_days: 14
          plugin_stars: yes
          plugin_followup: yes
          plugin_people: yes
          plugin_people_types: followers, following
          output_action: commit
          committer_branch: metrics
          committer_message: "chore: update metrics"
